apiVersion: v1
kind: Pod
metadata:
    name: cmd-entrypoing-pod
    labels:
        type: pod

spec:
    containers:
      - name: ubuntu-sleeper
        image: ubuntu
        command: ["sleep"]
        args: ["10"]
