apiVersion: v1
kind: Pod
metadata:
    name: my-pod
spec:
    containers:
      - name: my-container
        image: ubuntu
        command: ["sleep", "1000"]
        envFrom:
          - configMapRef:
                name: my-config-map
