apiVersion: v1
kind: Pod
metadata:
            name: just-pod-1
            labels:
                pod-label: pod-label-value
                specific: specific-value
spec:
            containers:
                - name: replica-set-container
                  image: nginx
