apiVersion: v1
kind: Pod
metadata:
    name: myapp-pod
    labels:
        app: myapp
        type: front-end

spec:
    containers:
      - name: nginx-container-1
        image: nginx:latest
      - name: mysql-container-2
        image: mysql:latest

# kubectl create -f pod-definition.yaml
