apiVersion: v1
kind: ReplicationController
metadata:
    name: rc-app
    labels:
        labelrc: labelrc-value1
spec:
    template:
        metadata:
            name: mypod-app
            labels:
                labelpod: labelpod-value1
        spec:
            containers:
                - name: nginx
                  image: nginx
    replicas: 3
