
apiVersion:  #v1 or apps/v1 etc, --> value : string
kind:        #pod, service, replicaSet, deployment  --> value : string
metadata:    #name, labels, etc  --> value : dictionary

spec:        #containers, etc --> value : dictionary
